In [2]:
import os
import soundfile as sf
import pandas as pd
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader,random_split
import librosa
import matplotlib.pyplot as plt
import random
from tqdm.notebook import tqdm as tqdm
from IPython.display import Audio, display

In [6]:
original_file = r"C:\Users\pkodu\Desktop\PCPT_bundle\SNDB\SNDB\wav\236_PIA_066_M.wav"
y, sr = librosa.load(original_file, sr=22005)

# Resample the audio to 8000 Hz
y_resampled = librosa.resample(y, orig_sr=sr, target_sr=8000)

# Save the resampled audio to a new WAV file
resampled_file = 'output.wav'
sf.write(resampled_file, y_resampled, 8000)

In [20]:
annotations_file = "./ann/SNDB_mini_annotations.csv"
ann_file =  pd.read_csv(annotations_file, sep=";")

In [21]:
ann_file

,unique_id,instrument,midi_pitch,dynamics,filename,sndb_filename
0,1,CLA,60,P,001_CLA_060_P.wav,10Cla1F060p_np___0.wav
1,2,CLA,60,M,002_CLA_060_M.wav,10Cla1F060m_np___0.wav
2,3,CLA,60,F,003_CLA_060_F.wav,10Cla1F060f_np___0.wav
3,4,CLA,61,P,004_CLA_061_P.wav,10Cla1F061p_np___0.wav
4,5,CLA,61,M,005_CLA_061_M.wav,10Cla1F061m_np___0.wav
...,...,...,...,...,...,...
499,500,VLN,82,M,500_VLN_082_M.wav,02Vio1F082m_np___0.wav
500,501,VLN,82,F,501_VLN_082_F.wav,02Vio1F082f_np___0.wav
501,502,VLN,83,P,502_VLN_083_P.wav,02Vio1F083p_np___0.wav
502,503,VLN,83,M,503_VLN_083_M.wav,02Vio1F083m_np___0.wav
503,504,VLN,83,F,504_VLN_083_F.wav,02Vio1F083f_np___0.wav

In [22]:
filtered_df = ann_file[(ann_file['dynamics'] == 'M') & (ann_file['midi_pitch'] >= 60) & (ann_file['midi_pitch'] <= 66)]

In [24]:
filtered_df = filtered_df.reset_index(drop=True)

In [25]:
filtered_df

,unique_id,instrument,midi_pitch,dynamics,filename,sndb_filename
0,2,CLA,60,M,002_CLA_060_M.wav,10Cla1F060m_np___0.wav
1,5,CLA,61,M,005_CLA_061_M.wav,10Cla1F061m_np___0.wav
2,8,CLA,62,M,008_CLA_062_M.wav,10Cla1F062m_np___0.wav
3,11,CLA,63,M,011_CLA_063_M.wav,10Cla1F063m_np___0.wav
4,14,CLA,64,M,014_CLA_064_M.wav,10Cla1F064m_np___0.wav
5,17,CLA,65,M,017_CLA_065_M.wav,10Cla1F065m_np___0.wav
6,20,CLA,66,M,020_CLA_066_M.wav,10Cla1F066m_np___0.wav
7,74,FLU,60,M,074_FLU_060_M.wav,11Flu1F060m_np___0.wav
8,77,FLU,61,M,077_FLU_061_M.wav,11Flu1F061m_np___0.wav
9,80,FLU,62,M,080_FLU_062_M.wav,11Flu1F062m_np___0.wav
10,83,FLU,63,M,083_FLU_063_M.wav,11Flu1F063m_np___0.wav
11,86,FLU,64,M,086_FLU_064_M.wav,11Flu1F064m_np___0.wav
12,89,FLU,65,M,089_FLU_065_M.wav,11Flu1F065m_np___0.wav
13,92,FLU,66,M,092_FLU_066_M.wav,11Flu1F066m_np___0.wav
14,146,OBO,60,M,146_OBO_060_M.wav,08Obo1F060m_np___0.wav
15,149,OBO,61,M,149_OBO_061_M.wav,08Obo1F061m_np___0.wav
16,152,OBO,62,M,152_OBO_062_M.wav,08Obo1F062m_np___0.wav
17,155,OBO,63,M,155_OBO_063_M.wav,08Obo1F063m_np___0.wav
18,158,OBO,64,M,158_OBO_064_M.wav,08Obo1F064m_np___0.wav
19,161,OBO,65,M,161_OBO_065_M.wav,08Obo1F065m_np___0.wav
20,164,OBO,66,M,164_OBO_066_M.wav,08Obo1F066m_np___0.wav
21,218,PIA,60,M,218_PIA_060_M.wav,01Pia1F060m_np___0.wav
22,221,PIA,61,M,221_PIA_061_M.wav,01Pia1F061m_np___0.wav
23,224,PIA,62,M,224_PIA_062_M.wav,01Pia1F062m_np___0.wav
24,227,PIA,63,M,227_PIA_063_M.wav,01Pia1F063m_np___0.wav
25,230,PIA,64,M,230_PIA_064_M.wav,01Pia1F064m_np___0.wav
26,233,PIA,65,M,233_PIA_065_M.wav,01Pia1F065m_np___0.wav
27,236,PIA,66,M,236_PIA_066_M.wav,01Pia1F066m_np___0.wav
28,290,TRP,60,M,290_TRP_060_M.wav,05Tru1F060m_np___0.wav
29,293,TRP,61,M,293_TRP_061_M.wav,05Tru1F061m_np___0.wav
30,296,TRP,62,M,296_TRP_062_M.wav,05Tru1F062m_np___0.wav
31,299,TRP,63,M,299_TRP_063_M.wav,05Tru1F063m_np___0.wav
32,302,TRP,64,M,302_TRP_064_M.wav,05Tru1F064m_np___0.wav
33,305,TRP,65,M,305_TRP_065_M.wav,05Tru1F065m_np___0.wav
34,308,TRP,66,M,308_TRP_066_M.wav,05Tru1F066m_np___0.wav
35,362,VLC,60,M,362_VLC_060_M.wav,03Cel1F060m_np___0.wav
36,365,VLC,61,M,365_VLC_061_M.wav,03Cel1F061m_np___0.wav
37,368,VLC,62,M,368_VLC_062_M.wav,03Cel1F062m_np___0.wav
38,371,VLC,63,M,371_VLC_063_M.wav,03Cel1F063m_np___0.wav
39,374,VLC,64,M,374_VLC_064_M.wav,03Cel1F064m_np___0.wav
40,377,VLC,65,M,377_VLC_065_M.wav,03Cel1F065m_np___0.wav
41,380,VLC,66,M,380_VLC_066_M.wav,03Cel1F066m_np___0.wav
42,434,VLN,60,M,434_VLN_060_M.wav,02Vio1F060m_np___0.wav
43,437,VLN,61,M,437_VLN_061_M.wav,02Vio1F061m_np___0.wav
44,440,VLN,62,M,440_VLN_062_M.wav,02Vio1F062m_np___0.wav
45,443,VLN,63,M,443_VLN_063_M.wav,02Vio1F063m_np___0.wav
46,446,VLN,64,M,446_VLN_064_M.wav,02Vio1F064m_np___0.wav
47,449,VLN,65,M,449_VLN_065_M.wav,02Vio1F065m_np___0.wav
48,452,VLN,66,M,452_VLN_066_M.wav,02Vio1F066m_np___0.wav

In [30]:
filtered_df.to_csv("test_annotation_file.csv", sep=";", index=False)

In [31]:
filtered_df

,unique_id,instrument,midi_pitch,dynamics,filename,sndb_filename
0,2,CLA,60,M,002_CLA_060_M.wav,10Cla1F060m_np___0.wav
1,5,CLA,61,M,005_CLA_061_M.wav,10Cla1F061m_np___0.wav
2,8,CLA,62,M,008_CLA_062_M.wav,10Cla1F062m_np___0.wav
3,11,CLA,63,M,011_CLA_063_M.wav,10Cla1F063m_np___0.wav
4,14,CLA,64,M,014_CLA_064_M.wav,10Cla1F064m_np___0.wav
5,17,CLA,65,M,017_CLA_065_M.wav,10Cla1F065m_np___0.wav
6,20,CLA,66,M,020_CLA_066_M.wav,10Cla1F066m_np___0.wav
7,74,FLU,60,M,074_FLU_060_M.wav,11Flu1F060m_np___0.wav
8,77,FLU,61,M,077_FLU_061_M.wav,11Flu1F061m_np___0.wav
9,80,FLU,62,M,080_FLU_062_M.wav,11Flu1F062m_np___0.wav
10,83,FLU,63,M,083_FLU_063_M.wav,11Flu1F063m_np___0.wav
11,86,FLU,64,M,086_FLU_064_M.wav,11Flu1F064m_np___0.wav
12,89,FLU,65,M,089_FLU_065_M.wav,11Flu1F065m_np___0.wav
13,92,FLU,66,M,092_FLU_066_M.wav,11Flu1F066m_np___0.wav
14,146,OBO,60,M,146_OBO_060_M.wav,08Obo1F060m_np___0.wav
15,149,OBO,61,M,149_OBO_061_M.wav,08Obo1F061m_np___0.wav
16,152,OBO,62,M,152_OBO_062_M.wav,08Obo1F062m_np___0.wav
17,155,OBO,63,M,155_OBO_063_M.wav,08Obo1F063m_np___0.wav
18,158,OBO,64,M,158_OBO_064_M.wav,08Obo1F064m_np___0.wav
19,161,OBO,65,M,161_OBO_065_M.wav,08Obo1F065m_np___0.wav
20,164,OBO,66,M,164_OBO_066_M.wav,08Obo1F066m_np___0.wav
21,218,PIA,60,M,218_PIA_060_M.wav,01Pia1F060m_np___0.wav
22,221,PIA,61,M,221_PIA_061_M.wav,01Pia1F061m_np___0.wav
23,224,PIA,62,M,224_PIA_062_M.wav,01Pia1F062m_np___0.wav
24,227,PIA,63,M,227_PIA_063_M.wav,01Pia1F063m_np___0.wav
25,230,PIA,64,M,230_PIA_064_M.wav,01Pia1F064m_np___0.wav
26,233,PIA,65,M,233_PIA_065_M.wav,01Pia1F065m_np___0.wav
27,236,PIA,66,M,236_PIA_066_M.wav,01Pia1F066m_np___0.wav
28,290,TRP,60,M,290_TRP_060_M.wav,05Tru1F060m_np___0.wav
29,293,TRP,61,M,293_TRP_061_M.wav,05Tru1F061m_np___0.wav
30,296,TRP,62,M,296_TRP_062_M.wav,05Tru1F062m_np___0.wav
31,299,TRP,63,M,299_TRP_063_M.wav,05Tru1F063m_np___0.wav
32,302,TRP,64,M,302_TRP_064_M.wav,05Tru1F064m_np___0.wav
33,305,TRP,65,M,305_TRP_065_M.wav,05Tru1F065m_np___0.wav
34,308,TRP,66,M,308_TRP_066_M.wav,05Tru1F066m_np___0.wav
35,362,VLC,60,M,362_VLC_060_M.wav,03Cel1F060m_np___0.wav
36,365,VLC,61,M,365_VLC_061_M.wav,03Cel1F061m_np___0.wav
37,368,VLC,62,M,368_VLC_062_M.wav,03Cel1F062m_np___0.wav
38,371,VLC,63,M,371_VLC_063_M.wav,03Cel1F063m_np___0.wav
39,374,VLC,64,M,374_VLC_064_M.wav,03Cel1F064m_np___0.wav
40,377,VLC,65,M,377_VLC_065_M.wav,03Cel1F065m_np___0.wav
41,380,VLC,66,M,380_VLC_066_M.wav,03Cel1F066m_np___0.wav
42,434,VLN,60,M,434_VLN_060_M.wav,02Vio1F060m_np___0.wav
43,437,VLN,61,M,437_VLN_061_M.wav,02Vio1F061m_np___0.wav
44,440,VLN,62,M,440_VLN_062_M.wav,02Vio1F062m_np___0.wav
45,443,VLN,63,M,443_VLN_063_M.wav,02Vio1F063m_np___0.wav
46,446,VLN,64,M,446_VLN_064_M.wav,02Vio1F064m_np___0.wav
47,449,VLN,65,M,449_VLN_065_M.wav,02Vio1F065m_np___0.wav
48,452,VLN,66,M,452_VLN_066_M.wav,02Vio1F066m_np___0.wav

In [11]:
ann_file =  pd.read_csv("test_annotation_file.csv")

In [12]:
ann_file.filename

0     002_CLA_060_M.wav
1     005_CLA_061_M.wav
2     008_CLA_062_M.wav
3     011_CLA_063_M.wav
4     014_CLA_064_M.wav
5     017_CLA_065_M.wav
6     020_CLA_066_M.wav
7     074_FLU_060_M.wav
8     077_FLU_061_M.wav
9     080_FLU_062_M.wav
10    083_FLU_063_M.wav
11    086_FLU_064_M.wav
12    089_FLU_065_M.wav
13    092_FLU_066_M.wav
14    146_OBO_060_M.wav
15    149_OBO_061_M.wav
16    152_OBO_062_M.wav
17    155_OBO_063_M.wav
18    158_OBO_064_M.wav
19    161_OBO_065_M.wav
20    164_OBO_066_M.wav
21    218_PIA_060_M.wav
22    221_PIA_061_M.wav
23    224_PIA_062_M.wav
24    227_PIA_063_M.wav
25    230_PIA_064_M.wav
26    233_PIA_065_M.wav
27    236_PIA_066_M.wav
28    290_TRP_060_M.wav
29    293_TRP_061_M.wav
30    296_TRP_062_M.wav
31    299_TRP_063_M.wav
32    302_TRP_064_M.wav
33    305_TRP_065_M.wav
34    308_TRP_066_M.wav
35    362_VLC_060_M.wav
36    365_VLC_061_M.wav
37    368_VLC_062_M.wav
38    371_VLC_063_M.wav
39    374_VLC_064_M.wav
40    377_VLC_065_M.wav
41    380_VLC_066_M.wav
42    434_VLN_060_M.wav
43    437_VLN_061_M.wav
44    440_VLN_062_M.wav
45    443_VLN_063_M.wav
46    446_VLN_064_M.wav
47    449_VLN_065_M.wav
48    452_VLN_066_M.wav
Name: filename, dtype: object

In [ ]:
len(